//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "detalle_factura")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub factura_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub producto_id: i32,
    #[sea_orm(column_type = "Decimal(Some((7, 2)))", nullable)]
    pub subtotal: Option<Decimal>,
    pub cantidad: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::factura::Entity",
        from = "Column::FacturaId",
        to = "super::factura::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Factura,
    #[sea_orm(
        belongs_to = "super::producto::Entity",
        from = "Column::ProductoId",
        to = "super::producto::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Producto,
}

impl Related<super::factura::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Factura.def()
    }
}

impl Related<super::producto::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Producto.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
