//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "factura")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nombre_cliente: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((7, 2)))", nullable)]
    pub total: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::detalle_factura::Entity")]
    DetalleFactura,
}

impl Related<super::detalle_factura::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DetalleFactura.def()
    }
}

impl Related<super::producto::Entity> for Entity {
    fn to() -> RelationDef {
        super::detalle_factura::Relation::Producto.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::detalle_factura::Relation::Factura.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
